apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: java-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-deployment
  template:
    metadata:
      labels:
        app: java-deployment
    spec:
      containers:
      - name: java-deployment
        image: thanushkiran12/javacicdapplication
        ports:
        - containerPort: 3000